version: '3.8'

services:
  db:
    image: "mariadb:10.4"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpw
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - my_network

  php-fpm:
    image: bitnami/php-fpm
    depends_on:
      - db
    volumes:
      - ./front_end:/var/www/html
    networks:
      - my_network

  web:
    image: 'httpd:latest'
    ports:
      - "8080:80"
    volumes:
      - ./front_end:/usr/local/apache2/htdocs
      - ./httpd_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./front_end:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
