version: '3.8'

services:
  db:
    image: "mariadb:10.4"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - my_network

  php-fpm:
    image: bitnami/php-fpm
    depends_on:
      - db
    volumes:
      - ./front_end:/var/www/html
    networks:
      - my_network

  web:
    image: 'httpd:latest'
    container_name: web
    volumes:
      - ./front_end:/usr/local/apache2/htdocs
      - ./httpd_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./front_end:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - my_network
    expose:
      - "80"
  web2:
    image: 'httpd:latest'
    container_name: web2
    volumes:
      - ./front_end:/usr/local/apache2/htdocs
      - ./httpd_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./front_end:/var/www/html
    networks:
      - my_network
    expose:
      - "80"
  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - my_network
    depends_on:
      - web
      - web2
networks:
  my_network:
    driver: bridge
